### ISSUE TITLE
Creating fat image for usb on windows ?

### ISSUE THREAD

**Issue by gomidas** [pbatard/uefi-simple#13]
Hi,

I finished my project.

I want to run it on a real hardware. Unfortunately I am not sure about correct way of creating image on windows10x64

Here steps mentioned:

Creating the FAT image
Next, create a FAT filesystem image.

```
dd if=/dev/zero of=fat.img bs=1k count=1440
mformat -i fat.img -f 1440 ::
mmd -i fat.img ::/EFI
mmd -i fat.img ::/EFI/BOOT
mcopy -i fat.img BOOTX64.EFI ::/EFI/BOOT
```
Running as a USB stick image
The FAT image can either be written directly to a USB stick and used in in a UEFI machine, or it can be run directly in QEMU:

`qemu-system-x86_64 -L OVMF_dir/ -bios OVMF.fd -usb -usbdevice disk::fat.img`

I am not good about this what should I do on windows ?

**Comment by pbatard** [comment]
1. Format the USB drive to FAT32
2. Copy the UEFI executable as \efi\boot\bootx64.efi (provided you are running on an x86_64 UEFI)

That's all.

For QEMU, refer to what debug.vbs does, or install Visual Studio 2019, open uefi-simple and select `Debug`, since we designed this project for testing with QEMU.

I will not provide any more help than that, as your questions are not directly related to uefi-simple, and you should be able to find the information you seek by spending a little bit of time searching for it.
