### ISSUE TITLE
uefi application and network

### ISSUE THREAD

**Issue by andrey-che** [pbatard/uefi-simple#14]
Thank you for your example!
Is it possible to make some http requests in such kind of applications?
Where to read about it? Or may be you could make example?

**Comment by pbatard** [comment]
UEFI provides a network stack with HTTP functionality. See https://uefi.org/specs/UEFI/2.10/29_Network_Protocols_ARP_and_DHCP.html#efi-http-protocols.

It'll be up to you to figure out how to use it or [find examples that do](https://github.com/search?q=EFI_HTTP_PROTOCOL+language%3AC&type=code&l=C).

**Comment by andrey-che** [comment]
There is encryption software DiskCryptor with support uefi boot load.
The UEFI boot loader loads config from local disk(EFI system partition). I want make it load from http server.
Firstly is is possible to make http queries and get data from network in efi executables ?

**Comment by pbatard** [comment]
Again, you're going to have to perform your own research. It's up to **you** to determine whether what you want to accomplish is feasible, not to other to invest time, that they usually don't have, to tell you whether they **think** that what you want to do can be done.

I understand that it's easy to imagine that people who published some work in the field you are after should be able to answer (what you probably believe to be) a simple question in a few minutes, but that's not how it works. I don't have more knowledge than you do about what can and cannot be accomplished through UEFI HTTP queries. I have **never** used networking in any of the UEFI executables I have produced. So, to answer what you think is a basic question, I would have to spend time doing the kind of research **you** should really be doing on your own, which, I genuinely don't have the scope for (because it's not because someone publishes something for free that their time is also free).

So, the very last thing I will tell you is that you seem to be trying to be replicating [a functionality of iPXE](https://ipxe.org/appnote/uefihttp), so you probably want to spend some time looking at the code of iPXE (that **might** perform something similar to what you want). And please do make sure that you actually invest a reasonable amount of time actually studying that code before you are tempted to contact the iPXE developers and try to lure them into conducting your project's exploratory work for you...

**Comment by andrey-che** [comment]
Sorry for the bothering. Of course you don't have to spend your time. I just asked in case you have quick answer. Thank you, I'll continue research
