### ISSUE TITLE
Debugging arguments not working properly in Visual Studio (2015)

### ISSUE THREAD

**Issue by makuc** [pbatard/uefi-simple#5]
When running this project using default configuration, TARGET became "-".

Looking through the script and manually printing messages, I figured out that WScript.Arguments(1) == "-", because my PATH  got cut-off in the middle... So the argument I was looking for as a TargetPlatform was located at a far later index (I think 4). I solved this by enclosing variables in Debugging --> Command Arguments in double quotes.

So for future ease, change Debugging --> Command Arguments to:
`//d .msvc\debug.vbs "$(TargetPath)" "$(PlatformShortName)"`

**Comment by pbatard** [comment]
Thanks for opening the issue here.

I was about to ask you to check the command argument line for invoking the Debug script, but you've already conducted that analysis and you're absolutely right: at the very least, the `$(TargetPath)` should be in quotes (and as a general rule, all variables should in case they contain a space). 

Let me fix just that - thanks a lot for looking into this issue further!

**Comment by makuc** [comment]
No problem. This is the least I can do after leeching from this project (at least for the moment -  i am still deciding whether to go for EDK II or GNU-EFI). :P

Anyway, thanks for that post at your website. It helped...a lot.

**Comment by pbatard** [comment]
Should be fixed now - thanks again!
